#!/usr/bin/expect -f

set pmem_bin    [lindex $argv 0];
set pmem_sz     [lindex $argv 1];
set dmem_bin    [lindex $argv 2];
set dmem_sz     [lindex $argv 3];
set set_flags   [lindex $argv 4];
set set_flags_p [lindex $argv 5];
set set_brk     [lindex $argv 6];

if { $::argc > 7 } {
    set mem_checks [lrange $argv 7 end];
}

spawn z80sim
expect ">>>"
send "x f\r"
expect "F = "
send "$set_flags\r"
expect ">>>"
send "x f'\r"
expect "F' = "
send "$set_flags_p\r"
expect ">>>"
send "r $pmem_bin,$dmem_sz\r"
expect ">>>"
send "r $dmem_bin,0\r"
expect ">>>"
send "b $set_brk\r"
expect ">>>"
send "l $dmem_sz\r"
expect ">>>"
send "g $dmem_sz\r"
expect ">>>"

if {[info exists mem_checks]} {
    foreach mem_check $::mem_checks {
        send "d $mem_check\r"
        expect ">>>"
    }
}

send "quit\r"
