#!/usr/bin/env python2

import math
import os
import random
import re
import subprocess
import sys
import uuid

# external programs
ASM = 'z80asm'
RUNSIM = 'ictest_runsim'

# limits
MAXTESTS = 2048
PROGMEM_SIZE = 4096
INT_DATAMEM_SIZE = 2**9
DATAMEM_SIZE = 2**13

# output files
ZEX_FILE = 'zex.txt'
TESTCASE_FILE = 'testcase.v'
PROGMEM_FILE = 'progmem.txt'
INT_DATAMEM1_FILE = 'datamem_int1.txt'
INT_DATAMEM2_FILE = 'datamem_int2.txt'
EXT_DATAMEM_FILE = 'datamem_ext.txt'

# temporary files
ASM_FILE = 'progmem.asm'
PROGMEM_BIN_FILE = 'progmem.bin'
DATAMEM_BIN_FILE = 'datamem.bin'

# bit widths
STATE_WIDTHS = {
    "INST1" : 8,
    "INST2" : 8,
    "INST3" : 8,
    "INST4" : 8,
    "A"     : 8,
    "A'"    : 8,
    "F"     : 8,
    "F'"    : 8,
    "BC"    : 16,
    "B'C'"  : 16,
    "DE"    : 16,
    "D'E'"  : 16,
    "HL"    : 16,
    "H'L'"  : 16,
    "IX"    : 16,
    "IY"    : 16,
    "SP"    : 16,
    "I"     : 8,
    "IFF"   : 1,
    "DUMMY" : 8
}

# program counter reset after voluntary jump
current_pc = 0

def parse_word(word, state):
    m = re.match('^([0-9a-fA-FxX]+)(b|h)$', word)
    if not m:
        raise ValueError("malformed word: {0}".format(word))

    value, base = m.groups()

    width = len(value) if base == 'b' else (len(value) * 4)
    if width != STATE_WIDTHS[state]:
        err = "state '{0}' has wrong bit width".format(state)
        raise ValueError(err)

    if base == 'b':
        return [int(digit, 2) if digit != 'x' else 'x'
                for digit in value]
    else:
        ret = []
        for digit in value:
            if digit == 'x':
                ret += ['x', 'x', 'x', 'x']
            else:
                ret += [int(b) for b in '{0:04b}'.format(int(digit, 16))]

        return ret

class StateVector:
    def __init__(self, states, bitvector):
        self.states = states
        self.bitvector = bitvector

    @classmethod
    def parse(cls, fmt):
        states = []
        bitvector = []

        for word in [w.strip() for w in fmt.split(',')]:
            m = re.match('^([\w\']+):([0-9a-fA-FxX]+(?:b|h))$', word)
            if not m:
                err = "malformed state vector element: {0}".format(word)
                raise ValueError(err)

            state, word = m.groups()
            if state not in STATE_WIDTHS:
               err = "unknown state in state vector: '{0}'".format(state)
               raise ValueError(err)

            states.append(state)
            bitvector += parse_word(word, state)

        return cls(states, bitvector)

    def copy(self):
        return StateVector(list(self.states), list(self.bitvector))

    def randomize(self):
        self.bitvector = [
            b if b != 'x' else random.randint(0, 1) for b in self.bitvector]


class SkipVector:
    def __init__(self, stateignore):
        self.stateignore = stateignore

    @classmethod
    def parse(cls, fmt):
        stateignore = {}

        for word in [w.strip() for w in fmt.split(',')]:
            word_fmt = '[0-9a-fA-FxX]+(?:b|h)'

            m = re.match('^(\w+):{{({0}(?:;{0})*)}}$'.format(word_fmt), word)
            if not m:
                 err = "malformed skip vector element: {0}".format(word)
                 raise ValueError(err)

            state, ignore = m.groups()
            if state not in STATE_WIDTHS:
                err = "unknown state in skip vector: '{0}'".format(state)
                raise ValueError(err)

            if state in stateignore:
                err = "duplicate state in skip vector: '{0}'".format(state)
                raise ValueError(err)

            stateignore[state] = []
            for word in [i.strip() for i in ignore.split(';')]:
                stateignore[state].append(parse_word(word, state))

        return SkipVector(stateignore)

    def check(self, vect):
        offs = 0
        for state in vect.states:
            width = STATE_WIDTHS[state]

            if state not in self.stateignore:
                offs += width
                continue

            value = vect.bitvector[offs:(offs + width)]

            for ignore in self.stateignore[state]:
                skip = True
                for v, i in zip(value, ignore):
                    if i == 'x':
                        continue

                    if v != i:
                        skip = False
                        break
                if skip:
                    return True

            offs += width

        return False


class MemCheck:
    MNEMONICS = {
        "(BC)"              : ["id", "BC"],
        "(DE)"              : ["id", "DE"],
        "(HL)"              : ["id", "HL"],
        "(SP)"              : ["id", "SP"],
        "(SP+1)"            : ["+", "SP", 1],
        "(SP-1)"            : ["+", "SP", -1],
        "(SP-2)"            : ["+", "SP", -2],
        "(CALL_PCH"         : ["+", "SP", -1],
        "CALL_PCL)"         : ["+", "SP", -2],
        "(IX+INST3)"        : ["+", "IX", "INST3"],
        "(IY+INST3)"        : ["+", "IY", "INST3"],
        "(INST3:INST2)"     : [":", "INST3", "INST2"],
        "([INST3:INST2]+1)" : [":+1", "INST3", "INST2"],
        "(INST4:INST3)"     : [":", "INST4", "INST3"],
        "([INST4:INST3]+1)" : [":+1", "INST4", "INST3"]
    }

    def __init__(self, states, pre, addrs=None, expected=None):
        self.states = states
        self.pre = pre
        self.addrs = addrs or []
        self.expected = expected or []

    @classmethod
    def parse(cls, fmt):
        states = []
        pre = {}
        for mnemonic in [m.strip() for m in fmt.split(',')]:
            if mnemonic not in MemCheck.MNEMONICS:
                err = "malformed memory check element: {0}".format(mnemonic)
                raise ValueError(err)

            states.append(mnemonic)

            for m in MemCheck.MNEMONICS[mnemonic][1:]:
                pre[m] = None

        return MemCheck(states, pre)

    def gen_addrs(self):
        for state in self.states:
            components = MemCheck.MNEMONICS[state]
            operator, operands = components[0], components[1:]

            operands = [self.pre[op] if isinstance(op, str) else op
                        for op in operands]

            if operator == 'id':
                addr = operands[0]
            elif operator == '+':
                disp = operands[1]
                if (disp & 0x80) == 0x80:
                    disp = -(((0xFF00 | disp) ^ 0xFFFF) + 1)
                addr = (operands[0] + disp) % (2**16)
            elif operator == ':':
                addr = 2**8 * operands[0] + operands[1]
            elif operator == ':+1':
                addr = 2**8 * operands[0] + operands[1] + 1
            else:
                err = "unrecognized memcheck operator: {0}"
                raise ValueError(err.format(operator))

            self.addrs.append(addr)

    def clear(self):
        for key in self.pre:
            self.pre[key] = None

        self.addrs = []
        self.expected = []


def generate_test(test_no, state_vector, options):
    ASM_STATE_FMT = {
        "A"      : " LD A,{0:03X}H\n",
        "A'"     : " EX AF,AF'\n LD A,{0:03X}H\n EX AF,AF'\n",
        "BC"     : " LD BC,{0:05X}H\n",
        "B'C'"   : " EXX\n LD BC,{0:05X}H\n EXX\n",
        "DE"     : " LD DE,{0:05X}H\n",
        "D'E'"   : " EXX\n LD DE,{0:05X}H\n EXX\n",
        "HL"     : " LD HL,{0:05X}H\n",
        "H'L'"   : " EXX\n LD HL,{0:05X}H\n EXX\n",
        "IX"     : " LD IX,{0:05X}H\n",
        "IY"     : " LD IY,{0:05X}H\n",
        "SP"     : " LD SP,{0:05X}H\n",
        "IFF_DI" : " DI\n",
        "IFF_EN" : " EI\n"
    }

    VUNIT_ELEMS = {
        "A"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.a",
        "A'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.ap",
        "F"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f",
        "F'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp",
        "S"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f[7]",
        "S'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp7[]",
        "Z"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f[6]",
        "Z'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp[6]",
        "H"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f[4]",
        "H'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp[4]",
        "PV"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f[2]",
        "PV'"  : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp[2]",
        "N"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f[1]",
        "N'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp[1]",
        "C"    : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.f[0]",
        "C'"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.fp[0]",
        "BC"   : "{ top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.b,"
                 " top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.c }",
        "B'C'" : "{ top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.bp,"
                 " top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.cp }",
        "DE"   : "{ top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.d, "
                 " top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.e }",
        "D'E'" : "{ top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.dp, "
                 " top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.ep }",
        "HL"   : "{ top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.h,"
                 " top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.l }",
        "H'L'" : "{ top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.hp,"
                 "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.lp }",
        "IX"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.ix",
        "IY"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.iy",
        "SP"   : "top_z80_i.z80_i.cpu_i.datapath_i.regfile_i.sp",
        "PC"   : "top_z80_i.z80_i.cpu_i.datapath_i.reg_pc_i.q",
        "I"    : "top_z80_i.z80_i.cpu_i.datapath_i.reg_int_ctrl_i.q",
        "IFF"  : "{ top_z80_i.z80_i.cpu_i.controller_i.fsm_i.int_iff1,"
                   " top_z80_i.z80_i.cpu_i.controller_i.fsm_i.int_iff2 }",
        "INT_DMEM1" : "top_z80_i.z80_i.memory_control_i."
                      "idram_i.SY180_256X8X1CM8_i1.Memory",
        "INT_DMEM2" : "top_z80_i.z80_i.memory_control_i."
                      "idram_i.SY180_256X8X1CM8_i2.Memory",
        "EXT_DMEM"  : "datamem_ext_i.datamem",
        "SWP"       : "datamem_swap"
    }

    VUNIT_STATE_FMT = {
        "A"     : "{0} = 8'h{1:02X};\n",
        "A'"    : "{0} = 8'h{1:02X};\n",
        "F"     : "{0} = 8'h{1:02X};\n",
        "F'"    : "{0} = 8'h{1:02X};\n",
        "BC"    : "{0} = 16'h{1:04X};\n",
        "B'C'"  : "{0} = 16'h{1:04X};\n",
        "DE"    : "{0} = 16'h{1:04X};\n",
        "D'E'"  : "{0} = 16'h{1:04X};\n",
        "HL"    : "{0} = 16'h{1:04X};\n",
        "H'L'"  : "{0} = 16'h{1:04X};\n",
        "IX"    : "{0} = 16'h{1:04X};\n",
        "IY"    : "{0} = 16'h{1:04X};\n",
        "PC"    : "{0} = 16'h{1:04X};\n",
        "SP"    : "{0} = 16'h{1:04X};\n",
        "I"     : "{0} = 8'h{1:02X};\n",
        "IFF"   : "{0} = 2'b{1:02b};\n",
        "INT_SWP" : "{{0}}[{0}'h{{1:02X}}] =\n"
                    "{{2}}[16'h{{3:02X}}];\n".format(
                        int(math.log(INT_DATAMEM_SIZE / 2, 2))),
        "EXT_SWP" : "{{0}}[{0}'h{{1:02X}}] =\n"
                    "{{2}}[16'h{{3:02X}}];\n".format(
                        int(math.log(DATAMEM_SIZE, 2)))
    }

    VUNIT_EXPECT_FMT = {
        "A"    : "unit.assert_eq8(8'h{0:02X}, {1},\n\"A ({2})\");\n",
        "A'"   : "unit.assert_eq8(8'h{0:02X}, {1},\n\"A' ({2})\");\n",
        "S"    : "unit.assert_eq(1'b{0}, {1},\n\"S ({2})\");\n",
        "S'"   : "unit.assert_eq(1'b{0}, {1},\n\"S' ({2})\");\n",
        "Z"    : "unit.assert_eq(1'b{0}, {1},\n\"Z ({2})\");\n",
        "Z'"   : "unit.assert_eq(1'b{0}, {1},\n\"Z' ({2})\");\n",
        "H"    : "unit.assert_eq(1'b{0}, {1},\n\"H ({2})\");\n",
        "H'"   : "unit.assert_eq(1'b{0}, {1},\n\"H' ({2})\");\n",
        "PV"   : "unit.assert_eq(1'b{0}, {1},\n\"PV ({2})\");\n",
        "PV'"  : "unit.assert_eq(1'b{0}, {1},\n\"PV' ({2})\");\n",
        "N"    : "unit.assert_eq(1'b{0}, {1},\n\"N ({2})\");\n",
        "N'"   : "unit.assert_eq(1'b{0}, {1},\n\"N' ({2})\");\n",
        "C"    : "unit.assert_eq(1'b{0}, {1},\n\"C ({2})\");\n",
        "C'"   : "unit.assert_eq(1'b{0}, {1},\n\"C' ({2})\");\n",
        "BC"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"BC ({2})\");\n",
        "B'C'" : "unit.assert_eq16(16'h{0:04X}, {1},\n\"B'C' ({2})\");\n",
        "DE"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"DE ({2})\");\n",
        "D'E'" : "unit.assert_eq16(16'h{0:04X}, {1},\n\"D'E' ({2})\");\n",
        "HL"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"HL ({2})\");\n",
        "H'L'" : "unit.assert_eq16(16'h{0:04X}, {1},\n\"H'L' ({2})\");\n",
        "IX"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"IX ({2})\");\n",
        "IY"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"IY ({2})\");\n",
        "I"    : "unit.assert_eq8(8'h{0:02X}, {1},\n\"I ({2})\");\n",
        "IFF"  : "unit.assert_eq2(2'b{0:02b}, {1},\n\"IFF ({2})\");\n",
        "SP"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"SP ({2})\");\n",
        "PC"   : "unit.assert_eq16(16'h{0:04X}, {1},\n\"PC ({2})\");\n",
        "INT_DMEM" : "unit.assert_eq8(8'h{{0:02X}}, {{1}}[{0}'h{{2:02X}}],\n"
                     "\"INT DMEM ({{3}})\");\n".format(
                         int(math.log(INT_DATAMEM_SIZE / 2, 2))),
        "EXT_DMEM" : "unit.assert_eq8(8'h{{0:02X}}, {{1}}[{0}'h{{2:02X}}],\n"
                     "\"EXT DMEM ({{3}})\");\n".format(
                         int(math.log(DATAMEM_SIZE, 2)))
    }

    VUNIT_FLAG_ORDER = ['S', 'Z', 'H', 'PV', 'N', 'C']

    global current_pc

    flagignore = options['flagignore']
    memcheck = options['memcheck']
    pccheck = options['pccheck']

    # z80sim input
    init_asm = ['START:\n']
    init_flags = '0x00'
    init_flags_p = '0x00'
    init_int_ctrl = '0x00'

    test_ops = []

    # ncsim input
    test_heading_fmt = "// BEGIN TESTCASE #{0}\n"
    test_heading = test_heading_fmt.format(test_no)

    test = [test_heading]
    progmem = [test_heading]

    offs = 0
    for state in state_vector.states:
        width = STATE_WIDTHS[state]
        binstr = ''.join(map(str, state_vector.bitvector[offs:(offs + width)]))
        binvalue = int(binstr, 2)

        if state.startswith('INST'):
            test_ops.append(chr(binvalue))
            progmem.append('{0:02X}\n'.format(binvalue))
        else:
            vunit_state_fmt = VUNIT_STATE_FMT[state]
            vunit_state = vunit_state_fmt.format(VUNIT_ELEMS[state], binvalue)
            test.append(vunit_state)

            if state == 'F':
                init_flags = '{0:02X}'.format(binvalue)
            elif state == "F'":
                init_flags_p = '{0:02X}'.format(binvalue)
            elif state == 'I':
                init_int_ctrl = '{0:02X}'.format(binvalue)
            elif state == 'IFF':
                if binvalue not in [0, 1]:
                    err = "unsupported IFF value: {0}".format(iff)
                    raise ValueError(err)

                if binvalue == 0:
                    init_asm.append(ASM_STATE_FMT['IFF_DI'])
                elif binvalue == 1:
                    init_asm.append(ASM_STATE_FMT['IFF_EN'])
            else:
                init_asm.append(ASM_STATE_FMT[state].format(binvalue))

        if memcheck and state in memcheck.pre:
            memcheck.pre[state] = binvalue

        offs += width

    # create reference simulation output
    asm_tmp = open(ASM_FILE, 'w+')
    bin_tmp = open(PROGMEM_BIN_FILE, 'w+')
    devnull = open(os.devnull, 'w')

    try:
        # assemble bytecode
        asm_tmp.writelines(init_asm)
        asm_tmp.close()

        z80asm = subprocess.Popen([ASM, ASM_FILE], stdout=devnull)
        z80asm.wait()

        # inject instruction bytes
        data = bin_tmp.read()
        instructions = [data[i:i+1] for i in range(len(data))]

        for op in test_ops:
            instructions.append(op)

        bin_tmp.seek(0)
        bin_tmp.write(b''.join(instructions))
        bin_tmp.close()

        # get breakpoint
        brk = DATAMEM_SIZE + len(instructions) - len(test_ops) - 3

        args = [
            RUNSIM,
            PROGMEM_BIN_FILE,
            '{0:04X}'.format(PROGMEM_SIZE),
            DATAMEM_BIN_FILE,
            '{0:04X}'.format(DATAMEM_SIZE),
            init_flags,
            init_flags_p,
            init_int_ctrl,
            '{0:04X}'.format(brk)
        ]

        if memcheck:
            memcheck.gen_addrs()
            args += ['{0:04x}'.format(a) for a in memcheck.addrs]

        z80sim = subprocess.Popen(args, stdout=subprocess.PIPE)
        z80sim.wait()

    finally:
        asm_tmp.close()
        bin_tmp.close()
        devnull.close()

        os.remove(ASM_FILE)
        os.remove(PROGMEM_BIN_FILE)

    # parse simulation results
    simout = z80sim.stdout.read()

    m = re.search(r'Software breakpoint.*\s+(.*)\n(.*)\n>>>', simout)
    if not m:
        err = "an error occured during simulation, check for illegal opcodes"
        raise ValueError(err)

    # obtain expected register values
    regs, values = m.groups()
    regs = [r.strip() for r in regs.split()]
    values = [v.strip() for v in values.split()]

    reg_expected = {}
    flag_expected = {}
    pc_expected = None
    for r, v in zip(regs, values):
        if r == 'SZHPNC':
            flags = [int(b, 2) for b in v]
            if not flagignore & 0x80:
                flag_expected['S'] = flags[0]
            if not flagignore & 0x40:
                flag_expected['Z'] = flags[1]
            if not flagignore & 0x10:
                flag_expected['H'] = flags[2]
            if not flagignore & 0x04:
                flag_expected['PV'] = flags[3]
            if not flagignore & 0x02:
                flag_expected['N'] = flags[4]
            if not flagignore & 0x01:
                flag_expected['C'] = flags[5]

        elif r == "A'F'":
            reg_expected["A'"] = int(v[:2], 16)

            flags = [int(b, 2) for b in '{0:08b}'.format(int(v[2:], 16))]
            if not flagignore & 0x80:
                flag_expected["S'"] = flags[0]
            if not flagignore & 0x40:
                flag_expected["Z'"] = flags[1]
            if not flagignore & 0x10:
                flag_expected["H'"] = flags[3]
            if not flagignore & 0x04:
                flag_expected["PV'"] = flags[5]
            if not flagignore & 0x02:
                flag_expected["N'"] = flags[6]
            if not flagignore & 0x01:
                flag_expected["C'"] = flags[7]

        elif r == 'PC' and pccheck != 'none':
            pc_expected = int(v, 16)

            # no jump occured (in all likelihood)
            if pc_expected == DATAMEM_SIZE + len(instructions) - 3:
                pc_expected = current_pc + len(test_ops)
            # correct expected PC in case of a relative jump
            elif pccheck == 'rel':
                pc_expected = (pc_expected - DATAMEM_SIZE - \
                               ((len(instructions) - 3) - len(test_ops)) + \
                               current_pc) % (2**16)

        elif r in state_vector.states:
            reg_expected[r] = int(v, 16)

    # optain expected memory locations
    if memcheck:
        pc_call = DATAMEM_SIZE + len(instructions) - 3
        pc_call_rel_hi = None
        pc_call_rel_lo = None

        for state, addr in zip(memcheck.states, memcheck.addrs):
            addr_hex = '{0:04X}'.format(addr)
            addr_lsn = int(addr_hex[3], 16)

            simout = simout[m.end():]
            m = re.search(r'Adr.*\n[0-9a-f]{4} - (.*)\t', simout)

            mem_row = [int(val, 16) for val in m.group(1).split()]
            mem_val = mem_row[addr_lsn]

            if state == '(CALL_PCH' and mem_val == (pc_call >> 8) & 0xFF:
                pc_call_rel_hi = ((current_pc + len(test_ops)) >> 8) & 0xFF

            elif state == 'CALL_PCL)' and mem_val == pc_call & 0xFF:
                pc_call_rel_lo = (current_pc + len(test_ops)) & 0xFF

            memcheck.expected.append(mem_val)

        if pc_call_rel_hi is not None and pc_call_rel_lo is not None:
             i_pc_hi = memcheck.states.index('(CALL_PCH')
             i_pc_lo = memcheck.states.index('CALL_PCL)')

             memcheck.expected[i_pc_hi] = pc_call_rel_hi
             memcheck.expected[i_pc_lo] = pc_call_rel_lo

    current_pc += len(test_ops)

    # add timeout loop to testbench code
    msg = "Testcase #{0}".format(test_no)
    waitloop = [
        "#(CLKPERIOD);",
        "",
        "loop_condition = 1'b1;",
        "loop_counter = 5'b0;",
        "while (loop_condition) begin",
        "    #(3 * CLKPERIOD / 4);",
        "    if (top_z80_i.z80_i.cpu_i.controller_i.fsm_i.state ==",
        "        FSM_STATE_INSTR_FETCH1_1) begin",
        "        loop_condition = 1'b0;",
        "    end else begin",
        "        #(CLKPERIOD / 4);",
        "        loop_counter = loop_counter + 1;",
        "        if (loop_counter == 5'b11111)",
        "            unit.fail(\"Instruction not terminating ({0})\");".format(msg),
        "    end",
        "end"
    ]

    test.append('\n{0}\n\n'.format('\n'.join(waitloop)))

    # add register assertions to testbench code
    for state in state_vector.states:
        if state in ['INST1', 'INST2', 'INST3', 'INST4', 'F', "F'", "DUMMY"]:
            continue

        fmt = VUNIT_EXPECT_FMT[state]
        msg = "Testcase #{0} {1}".format(test_no, uuid.uuid4())
        expect = fmt.format(reg_expected[state], VUNIT_ELEMS[state], msg)

        test.append(expect)

    for flag in VUNIT_FLAG_ORDER:
        if flag not in flag_expected:
            continue

        fmt = VUNIT_EXPECT_FMT[flag]
        msg = "Testcase #{0} {1}".format(test_no, uuid.uuid4())
        expect = fmt.format(flag_expected[flag], VUNIT_ELEMS[flag], msg)

        test.append(expect)

    # add memory assertions to testbench code
    if memcheck:
        test.append('\n')

        for addr, exp in zip(memcheck.addrs, memcheck.expected):
            msg = "Testcase #{0} {1}".format(test_no, uuid.uuid4())

            if addr < INT_DATAMEM_SIZE / 2:
                fmt = VUNIT_EXPECT_FMT['INT_DMEM']
                expect = fmt.format(exp, VUNIT_ELEMS['INT_DMEM1'], addr, msg)
            elif addr < INT_DATAMEM_SIZE:
                addr -= INT_DATAMEM_SIZE / 2
                fmt = VUNIT_EXPECT_FMT['INT_DMEM']
                expect = fmt.format(exp, VUNIT_ELEMS['INT_DMEM2'], addr, msg)
            elif addr < DATAMEM_SIZE:
                fmt = VUNIT_EXPECT_FMT['EXT_DMEM']
                expect = fmt.format(exp, VUNIT_ELEMS['EXT_DMEM'], addr, msg)
            else:
                return None

            test.append(expect)

        for addr in memcheck.addrs:
            if addr < INT_DATAMEM_SIZE / 2:
                fmt = VUNIT_STATE_FMT['INT_SWP']
                swp = fmt.format(VUNIT_ELEMS['INT_DMEM1'], addr,
                                 VUNIT_ELEMS['SWP'], addr)
            elif addr < INT_DATAMEM_SIZE:
                fmt = VUNIT_STATE_FMT['INT_SWP']
                addr2 = addr - INT_DATAMEM_SIZE / 2
                swp = fmt.format(VUNIT_ELEMS['INT_DMEM2'], addr2,
                                 VUNIT_ELEMS['SWP'], addr)
            else:
                fmt = VUNIT_STATE_FMT['EXT_SWP']
                swp = fmt.format(VUNIT_ELEMS['EXT_DMEM'], addr,
                                 VUNIT_ELEMS['SWP'], addr)

            test.append(swp)

    # add program counter assertion to testbench code
    if pccheck != 'none':
        test.append('\n')

        fmt = VUNIT_EXPECT_FMT['PC']
        msg = "Testcase #{0} {1}".format(test_no, uuid.uuid4())
        test.append(fmt.format(pc_expected, VUNIT_ELEMS['PC'], msg))

        fmt = VUNIT_STATE_FMT['PC']
        test.append(fmt.format(VUNIT_ELEMS['PC'], current_pc))

    test.append("\n#(CLKPERIOD / 4);\n\n");

    return test, progmem


if __name__ == '__main__':
    # read test description
    with open(ZEX_FILE) as infile:
        zex = infile.read()

    # strip comments and trailing whitespace
    zex = re.sub(r'(?m)\s*(#.*)?$', '', zex)

    # remove empty lines
    zex = '\n'.join([line for line in zex.split('\n') if line])

    options = {
        'name' : None,
        'desc' : None,
        'base' : None,
        'cycle' : None,
        'skip' : None,
        'repeat' : 0,
        'memcheck' : None,
        'pccheck' : 'none',
        'flagignore' : 0x00
    }

    seen_options = set()
    for i, line in enumerate(zex.split('\n')):
        if i == 0 and line == 'MANUAL':
            print("MANUAL specified, skipping automatic test generation")
            exit()

        m = re.match('^(\w+):\s*(.*)$', line)
        if not m:
            raise ValueError("syntax error in line {0} of zex file".format(i))

        option, value = m.groups()
        if option not in options:
            raise ValueError("unknown option: '{0}'".format(option))
        if option in seen_options:
            raise ValueError("duplicate option: '{0}'".format(option))

        def parse_flagignore(fmt):
            m = re.match('([0-9a-fA-F]{2})h', fmt)
            if not m:
                raise ValueError("invalid flagignore mask: '{0}'".format(fmt))

            return int(m.group(1), 16)

        def parse_pccheck(fmt):
            if fmt not in ['none', 'abs', 'rel']:
                raise ValueError("invalid pccheck value")

            return fmt

        parse = {
            'base'       : StateVector.parse,
            'cycle'      : StateVector.parse,
            'skip'       : SkipVector.parse,
            'repeat'     : int,
            'memcheck'   : MemCheck.parse,
            'pccheck'    : parse_pccheck,
            'flagignore' : parse_flagignore
        }.get(option, str)

        options[option] = parse(value)
        seen_options.add(option)

    mandatory_options = ['name', 'desc', 'base']
    for option in mandatory_options:
        if options[option] is None:
            raise ValueError("missing mandatory option {0}", option)

    # state vector cycle positions
    cycle_pos = [i for i, b in enumerate(options['cycle'].bitvector) if b == 1]
    cycles = list(range(2**len(cycle_pos)))

    if (len(cycles) > MAXTESTS):
        err = "trying to generate {0} tests (maximum is {1})"
        raise ValueError(err.format(len(cycles), MAXTESTS))

    # generate testcase files
    testcase_out = open(TESTCASE_FILE, 'w+')
    progmem_out = open(PROGMEM_FILE, 'w+')
    int_datamem1_out = open(INT_DATAMEM1_FILE, 'w+')
    int_datamem2_out = open(INT_DATAMEM2_FILE, 'w+')
    ext_datamem_out = open(EXT_DATAMEM_FILE, 'w+')
    datamem_bin_out = open(DATAMEM_BIN_FILE, 'w+')

    # create random data memory
    int_datamem1 = []
    int_datamem2 = []
    ext_datamem = []
    datamem_bin = [255, 0, 0]
    for addr in range(DATAMEM_SIZE):
        rand_val = random.randint(0, 255)

        if addr < INT_DATAMEM_SIZE / 2:
            int_datamem1.append('@{0:04X} {1:02X}\n'.format(addr, rand_val))
        elif addr < INT_DATAMEM_SIZE:
            addr -= INT_DATAMEM_SIZE / 2
            int_datamem2.append('@{0:04X} {1:02X}\n'.format(addr, rand_val))
        elif addr < DATAMEM_SIZE:
            ext_datamem.append('@{0:04X} {1:02X}\n'.format(addr, rand_val))

        datamem_bin.append(rand_val)

    datamem_bin = bytes(bytearray(datamem_bin))

    try:
        # fill data memory
        int_datamem1_out.writelines(int_datamem1)
        int_datamem1_out.close()
        int_datamem2_out.writelines(int_datamem2)
        int_datamem2_out.close()
        ext_datamem_out.writelines(ext_datamem)
        ext_datamem_out.close()

        datamem_bin_out.write(datamem_bin)
        datamem_bin_out.close()

        # begin creating testcase file
        testcase_out.write('unit.start("{0} ({1})");\n\n'.format(
            options['name'], options['desc']))

        repetitions = options['repeat'] + 1
        tests_total = len(cycles) * repetitions

        test_no = 0
        for cycle in cycles:
            for _ in range(repetitions):
                # display progress
                if options['skip']:
                    progress = "\rGenerating test {0}".format(test_no + 1)
                else:
                    progress = "\rGenerating test {0}/{1}".format(test_no + 1,
                                                                  tests_total)
                sys.stdout.write(progress)
                sys.stdout.flush()

                # create state vector variant
                done = False
                skip = False
                while not done:
                    vect = options['base'].copy()

                    if len(cycle_pos) > 0:
                        setbits = '{0:b}'.format(cycle).zfill(len(cycle_pos))
                        for i, b in enumerate(setbits):
                            vect.bitvector[cycle_pos[i]] = int(b)

                    vect.randomize()

                    # potentially skip specific state vectors
                    if options['skip'] and options['skip'].check(vect):
                        skip = True
                        break

                    # reset any memory checks
                    if options['memcheck']:
                        options['memcheck'].clear()

                    # generate test and update files
                    result = generate_test(test_no, vect, options)

                    if result is not None:
                        test, progmem = result
                        done = True

                if not skip:
                    testcase_out.writelines(test)
                    progmem_out.writelines(progmem)
                    test_no += 1

        testcase_out.write('unit.finish("{0} ({1})");\n'.format(
            options['name'], options['desc']))

        sys.stdout.write('\n')

    finally:
        testcase_out.close()
        progmem_out.close()
        int_datamem1_out.close()
        int_datamem2_out.close()
        ext_datamem_out.close()
        datamem_bin_out.close()

        os.remove(DATAMEM_BIN_FILE)
