#!/usr/bin/expect -f

set prog_bin    [lindex $argv 0];
set dmem_bin    [lindex $argv 1];
set dmem_sz     [lindex $argv 2];
set set_flags   [lindex $argv 3];
set set_flags_p [lindex $argv 4];

if { $::argc > 5 } {
    set mem_checks [lrange $argv 5 end];
}

spawn z80sim
expect ">>>"
send "x f\r"
expect "F = "
send "$set_flags\r"
expect ">>>"
send "x f'\r"
expect "F' = "
send "$set_flags_p\r"
expect ">>>"
send "r $prog_bin,$dmem_sz\r"
expect ">>>"
send "r $dmem_bin,0\r"
expect ">>>"
send "g $dmem_sz\r"
expect ">>>"

if {[info exists mem_checks]} {
    foreach mem_check $::mem_checks {
        send "d $mem_check\r"
        expect ">>>"
    }
}

send "quit\r"
